import 'package:flutter/foundation.dart';
import '../core/models/quiz_session.dart';
import '../core/models/question.dart';
import '../core/services/wikipedia_service.dart';
import '../core/services/question_generator.dart';
import '../core/services/llm_question_service.dart';

enum QuizState { idle, loading, ready, answering, complete, error }

class QuizProvider extends ChangeNotifier {
  final WikipediaService _wikipedia;
  final QuestionGenerator _generator;
  final LlmQuestionService? _llm;

  QuizState _state = QuizState.idle;
  QuizSession? _session;
  String? _errorMessage;
  bool _showingFeedback = false;
  bool? _lastAnswerCorrect;

  QuizProvider({
    required WikipediaService wikipedia,
    LlmQuestionService? llm,
  })  : _wikipedia = wikipedia,
        _generator = QuestionGenerator(),
        _llm = llm ?? LlmQuestionService();

  QuizState get state => _state;
  QuizSession? get session => _session;
  String? get errorMessage => _errorMessage;
  bool get showingFeedback => _showingFeedback;
  bool? get lastAnswerCorrect => _lastAnswerCorrect;

  Future<void> startQuiz(String topic) async {
    _state = QuizState.loading;
    _errorMessage = null;
    _session = null;
    notifyListeners();

    try {
      final article = await _wikipedia.getArticle(topic);
      final content = await _wikipedia.getFullContent(topic);

      List<Question> questions;
      List<String> keyFacts;

      try {
        final result = await _llm!.generate(topic, content);
        questions = result.questions;
        keyFacts = result.keyFacts;
        debugPrint('Questions generated by Ollama (${questions.length})');
      } catch (e) {
        debugPrint('LLM unavailable, using local generator: $e');
        questions = _generator.generateQuestions(topic, content);
        keyFacts = _generator.extractKeyFacts(content);
      }

      if (questions.isEmpty) {
        throw Exception('Could not generate questions for this article. Try a different topic.');
      }

      final enriched = await Future.wait(
        questions.map((q) async {
          final term = _searchTermFor(q);
          if (term == null) return q;
          final url = await _wikipedia.getImageForTerm(term);
          return url != null ? q.copyWith(imageUrl: url) : q;
        }),
      );

      _session = QuizSession(
        topic: article.title,
        topicSummary: article.summary,
        imageUrl: article.imageUrl,
        questions: enriched,
        keyFacts: keyFacts,
      );
      _state = QuizState.ready;
    } catch (e) {
      _errorMessage = e.toString();
      _state = QuizState.error;
    }

    notifyListeners();
  }

  void beginAnswering() {
    _state = QuizState.answering;
    notifyListeners();
  }

  void submitAnswer(dynamic answer) {
    if (_session == null || _session!.currentQuestion == null) return;

    final isCorrect = _session!.currentQuestion!.checkAnswer(answer);
    _lastAnswerCorrect = isCorrect;
    _showingFeedback = true;
    _session = _session!.answerQuestion(isCorrect);

    notifyListeners();
  }

  void nextQuestion() {
    _showingFeedback = false;
    _lastAnswerCorrect = null;

    if (_session!.isComplete) {
      _state = QuizState.complete;
    }

    notifyListeners();
  }

  String? _searchTermFor(Question q) {
    final numericOnly = RegExp(r'^\d+$');
    switch (q.type) {
      case QuestionType.fillBlank:
        final a = q.answer ?? '';
        return numericOnly.hasMatch(a) ? null : a;
      case QuestionType.multipleChoice:
        final correct = q.options?[q.correctIndex ?? 0] ?? '';
        return numericOnly.hasMatch(correct) ? null : correct;
      case QuestionType.trueFalse:
        final words = q.question.split(RegExp(r'\s+'));
        for (int i = 1; i < words.length; i++) {
          final w = words[i].replaceAll(RegExp(r'[^a-zA-Z]'), '');
          if (w.length > 2 &&
              w[0] == w[0].toUpperCase() &&
              w[0] != w[0].toLowerCase()) {
            return w;
          }
        }
        return null;
    }
  }

  void reset() {
    _state = QuizState.idle;
    _session = null;
    _errorMessage = null;
    _showingFeedback = false;
    _lastAnswerCorrect = null;
    notifyListeners();
  }
}
